# Generated by Django 5.1.5 on 2025-02-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Логин пользователя')),
                ('balance', models.DecimalField(decimal_places=3, default=100, max_digits=100, verbose_name='Баланс')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Покупатели',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название игры')),
                ('cost', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Цена')),
                ('size', models.DecimalField(decimal_places=3, max_digits=30)),
                ('description', models.TextField(blank=True)),
                ('age_limited', models.BooleanField(default=False)),
                ('buyer', models.ManyToManyField(related_name='games', related_query_name='game', to='task1.buyer')),
            ],
            options={
                'verbose_name': 'Игры',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
